/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mateo Vasquez Morales (https://sketchfab.com/teoxx1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-diorama-ae8b43a499c3449ba7755bba77c9a4a4
Title: Fantasy Diorama
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Hero3D = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/diorame/novo1.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group
          name='Sketchfab_model'
          position={[-3.701, -0.621, -0.306]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group
                name='Mball002_0'
                position={[-13.35, -12.407, 15.172]}
                rotation={[0, -0.415, 0]}
                scale={[1.341, 1.341, 1.073]}
              >
                <mesh
                  name='Object_4'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name='Mball001_1'
                position={[-0.68, -23.023, 8.28]}
                scale={[1.18, 1.18, 0.945]}
              >
                <mesh
                  name='Object_6'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name='Mball003_2'
                position={[15.479, -7.355, 11.123]}
                rotation={[0, 0.801, 0]}
                scale={[1.18, 1.18, 0.945]}
              >
                <mesh
                  name='Object_8'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name='Mball004_3'
                position={[6.882, -15.758, -8.174]}
                rotation={[Math.PI, -0.801, Math.PI]}
                scale={[-1.516, -1.003, -0.945]}
              >
                <mesh
                  name='Object_10'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name='Mball005_4'
                position={[-8.661, -15.314, -13.644]}
                rotation={[0, 0.018, 0]}
                scale={[-1.516, -1.175, -0.945]}
              >
                <mesh
                  name='Object_12'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group
                name='Mball006_5'
                position={[-3.572, -28.679, -7.161]}
                rotation={[0, 0.018, 0]}
                scale={[-1.174, -0.911, -0.732]}
              >
                <mesh
                  name='Object_14'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials["Material.002"]}
                />
              </group>
              <group name='Textura_Hoja1_6' position={[-32.751, -0.174, 0]}>
                <mesh
                  name='Object_16'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.Textura_Hoja1}
                />
              </group>
              <group name='Textura_Hoja2_7' position={[-32.038, 0, 0]}>
                <mesh
                  name='Object_18'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.Textura_Hoja2}
                />
              </group>
              <group name='Flor1_8' position={[-35.114, 0, 0]}>
                <mesh
                  name='Object_20'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.Flor1}
                />
              </group>
              <group name='Flor2_9' position={[-34.014, 0, 0]}>
                <mesh
                  name='Object_22'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.Flor2}
                />
              </group>
              <group
                name='Cube_10'
                position={[0, -0.003, 0]}
                scale={[5.696, 1.913, 5.696]}
              >
                <mesh
                  name='Object_24'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.Fachada}
                />
              </group>
              <group
                name='Cube002_11'
                position={[1.545, 5.341, 0.01]}
                scale={[3.716, 1.834, 5.013]}
              >
                <mesh
                  name='Object_26'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.Fachada}
                />
              </group>
              <group
                name='Cube003_12'
                position={[-7.468, 5.298, 0]}
                scale={[3.265, 1.32, 5.696]}
              >
                <mesh
                  name='Object_28'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.Fachada}
                />
              </group>
              <group
                name='Cube010_13'
                position={[-12.718, 5.364, 0]}
                scale={[0.216, 0.522, 5.499]}
              >
                <mesh
                  name='Object_30'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube023_15'
                position={[-2.948, 8.958, 5.23]}
                rotation={[0, 0, 0.532]}
                scale={0.368}
              >
                <mesh
                  name='Object_32'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube024_16'
                position={[3.522, 8.837, 5.144]}
                rotation={[0, 0, -0.563]}
                scale={[-0.368, 0.368, 0.368]}
              >
                <mesh
                  name='Object_34'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube030_17'
                position={[-8.77, 4.087, -0.026]}
                rotation={[0, 0, -0.558]}
                scale={[0.419, 0.352, 0.352]}
              >
                <mesh
                  name='Object_36'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.Pilares}
                />
              </group>
              <group
                name='Cube031_18'
                position={[3.422, 12.563, 0.29]}
                scale={[0.159, 0.376, 0.159]}
              >
                <mesh
                  name='Object_38'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name='Cube005_19'
                position={[3.747, 11.402, 5.431]}
                scale={[0.4, 4.205, 0.32]}
              >
                <mesh
                  name='Object_40'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube007_20'
                position={[-2.976, 11.402, 5.249]}
                scale={[0.4, 4.205, 0.32]}
              >
                <mesh
                  name='Object_42'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube009_21'
                position={[0.428, 11.1, 5.424]}
                scale={0.399}
              >
                <mesh
                  name='Object_44'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube025_22'
                position={[0.573, 17.62, 0]}
                scale={0.572}
              >
                <mesh
                  name='Object_46'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube076_23'
                position={[0.697, 19.581, 3.99]}
                rotation={[-1.158, 0, 0]}
                scale={[0.78, 0.804, 0.05]}
              >
                <mesh
                  name='Object_48'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials.Tejas}
                />
              </group>
              <group
                name='Cube046_24'
                position={[0.276, 22.439, 0.003]}
                rotation={[-0.864, 0, 0]}
                scale={[5.163, 0.615, 0.615]}
              >
                <mesh
                  name='Object_50'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials.Maderos_Techo}
                />
              </group>
              <group
                name='Cube047_25'
                position={[-8.128, 15.608, 0.162]}
                scale={[5.291, 0.697, 0.697]}
              >
                <mesh
                  name='Object_52'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials.Maderos_Techo}
                />
              </group>
              <group
                name='Cube045_26'
                position={[-8.897, 13.868, 3.359]}
                rotation={[0.246, 0, Math.PI]}
                scale={[0.657, 0.045, 0.743]}
              >
                <mesh
                  name='Object_54'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials.Tejas1}
                />
              </group>
              <group
                name='Cube001_27'
                position={[2.749, 7.85, 0.01]}
                scale={[3.716, 1.834, 5.013]}
              >
                <mesh
                  name='Object_56'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials.Puertas}
                />
              </group>
              <group
                name='Cube050_28'
                position={[-1.178, 5.378, 5.644]}
                scale={[0.445, 0.553, 0.445]}
              >
                <mesh
                  name='Object_58'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cylinder008_29'
                position={[5.008, 6.646, -5.595]}
                scale={[0.069, 0.877, 0.069]}
              >
                <mesh
                  name='Object_60'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials.Baranda}
                />
              </group>
              <group
                name='Cube011_30'
                position={[3.408, 5.395, -4.148]}
                scale={[0.445, 0.553, 0.445]}
              >
                <mesh
                  name='Object_62'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube052_31'
                position={[-6.407, 0.393, 5.624]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.352, 0.534, 0.32]}
              >
                <mesh
                  name='Object_64'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.Ladrillos}
                />
              </group>
              <group
                name='Marco005_32'
                position={[0.411, 13.742, 5.496]}
                scale={0.224}
              >
                <mesh
                  name='Object_66'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials.Ventanas2}
                />
              </group>
              <group
                name='Cube055_33'
                position={[9.457, 2.929, -0.195]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[0.248, 0.203, 0.336]}
              >
                <mesh
                  name='Object_68'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.Ventanas1}
                />
              </group>
              <group
                name='Cube057_34'
                position={[9.464, 2.952, -0.266]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[0.248, 0.203, 0.336]}
              >
                <mesh
                  name='Object_70'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.Ventanas1}
                />
              </group>
              <group
                name='Cube070_35'
                position={[1.801, 3.017, -5.799]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[0.269, 0.203, 0.336]}
              >
                <mesh
                  name='Object_72'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials.Ventanas1}
                />
              </group>
              <group
                name='Cube071_36'
                position={[1.801, 2.917, -5.783]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[0.269, 0.203, 0.336]}
              >
                <mesh
                  name='Object_74'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={materials.Ventanas1}
                />
              </group>
              <group
                name='Cube074_37'
                position={[-12.684, 8.411, -0.206]}
                rotation={[Math.PI / 2, -1.398, Math.PI / 2]}
                scale={[0.293, 0.239, 0.397]}
              >
                <mesh
                  name='Object_76'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials.Ventanas1}
                />
              </group>
              <group
                name='Cube075_38'
                position={[-12.543, 9.11, -0.268]}
                rotation={[Math.PI / 2, -1.398, Math.PI / 2]}
                scale={[0.293, 0.239, 0.397]}
              >
                <mesh
                  name='Object_78'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_78.geometry}
                  material={materials.Ventanas1}
                />
              </group>
              <group
                name='Puerta001_39'
                position={[2.547, 2.45, 5.214]}
                scale={[0.151, 0.151, 0.048]}
              >
                <mesh
                  name='Object_80'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_80.geometry}
                  material={materials.Puertas}
                />
              </group>
              <group
                name='Puerta002_40'
                position={[2.539, 2.911, 5.424]}
                scale={[0.151, 0.151, 0.048]}
              >
                <mesh
                  name='Object_82'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={materials.Puertas}
                />
              </group>
              <group
                name='Puerta003_41'
                position={[3.625, 1.433, 5.429]}
                scale={[0.151, 0.151, 0.048]}
              >
                <mesh
                  name='Object_84'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_84.geometry}
                  material={materials.Puertas}
                />
              </group>
              <group
                name='Puerta004_42'
                position={[1.438, 1.737, 5.498]}
                scale={[0.151, 0.151, 0.048]}
              >
                <mesh
                  name='Object_86'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_86.geometry}
                  material={materials.Puertas}
                />
              </group>
              <group
                name='Cube012_43'
                position={[-2.948, 8.958, -5.364]}
                rotation={[-Math.PI, 0, 2.609]}
                scale={[-0.368, 0.368, 0.23]}
              >
                <mesh
                  name='Object_88'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_88.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube027_44'
                position={[3.522, 8.837, -5.109]}
                rotation={[-Math.PI, 0, -2.579]}
                scale={[0.368, 0.368, 0.439]}
              >
                <mesh
                  name='Object_90'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_90.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube028_45'
                position={[3.747, 11.402, -5.485]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[-0.4, 4.205, 0.328]}
              >
                <mesh
                  name='Object_92'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_92.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube032_46'
                position={[-2.976, 11.402, -5.297]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[-0.4, 4.205, 0.328]}
              >
                <mesh
                  name='Object_94'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={materials.Maderos}
                />
              </group>
              <group
                name='Cube008_47'
                position={[-8.77, 4.087, -0.026]}
                rotation={[0, 0, -0.558]}
                scale={[0.419, 0.352, 0.352]}
              >
                <mesh
                  name='Object_96'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_96.geometry}
                  material={materials.Pilares}
                />
              </group>
              <group
                name='Marco004_48'
                position={[-7.541, 8.872, 5.534]}
                rotation={[0.053, 0, 0]}
                scale={0.224}
              >
                <mesh
                  name='Object_98'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_98.geometry}
                  material={materials.Ventanas2}
                />
              </group>
              <group
                name='Marco006_49'
                position={[-2.367, 2.907, 5.834]}
                rotation={[0.011, 0, 0]}
                scale={0.21}
              >
                <mesh
                  name='Object_100'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={materials.Ventanas2}
                />
              </group>
              <group name='Icosphere_50' position={[-30.314, 0, 0]}>
                <mesh
                  name='Object_102'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_102.geometry}
                  material={materials.Transparent}
                />
              </group>
              <group
                name='Cube059_51'
                position={[3.842, 8.731, -3.482]}
                scale={[0.212, 0.276, 0.201]}
              >
                <mesh
                  name='Object_104'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_104.geometry}
                  material={materials.Lamparas_Prop}
                />
              </group>
              <group
                name='Cube060_52'
                position={[5.823, 2.775, 5.839]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.212, 0.276, 0.201]}
              >
                <mesh
                  name='Object_106'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={materials.Lamparas_Prop}
                />
              </group>
              <group
                name='Cube058_53'
                position={[-11.5, 0.924, 1.067]}
                rotation={[0, -0.327, 0]}
              >
                <mesh
                  name='Object_108'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_108.geometry}
                  material={materials.Props1}
                />
              </group>
              <group
                name='Cube006_54'
                position={[-11.5, 0.924, -2.048]}
                rotation={[Math.PI, -1.544, Math.PI]}
              >
                <mesh
                  name='Object_110'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_110.geometry}
                  material={materials.Props1}
                />
              </group>
              <group
                name='Cylinder002_55'
                position={[-8.314, 1.2, 6.569]}
                rotation={[Math.PI / 2, 0, -0.671]}
                scale={[0.481, 1.183, 0.481]}
              >
                <mesh
                  name='Object_112'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_112.geometry}
                  material={materials.Props1}
                />
              </group>
              <group
                name='Plane001_56'
                position={[-21.186, 0, -3.193]}
                rotation={[0, 0.833, 0]}
                scale={1.593}
              >
                <mesh
                  name='Object_114'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_114.geometry}
                  material={materials["Textura_Hoja1.002"]}
                />
                <mesh
                  name='Object_115'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_115.geometry}
                  material={materials["Textura_Hoja2.002"]}
                />
              </group>
              <group
                name='Plane002_57'
                position={[-16.054, 0.419, 11.946]}
                rotation={[0, 0.625, 0]}
                scale={1.593}
              >
                <mesh
                  name='Object_117'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_117.geometry}
                  material={materials["Textura_Hoja1.002"]}
                />
                <mesh
                  name='Object_118'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_118.geometry}
                  material={materials["Textura_Hoja2.002"]}
                />
              </group>
              <group
                name='Plane003_58'
                position={[14.613, 0.442, -9.908]}
                rotation={[0, -1.422, 0]}
                scale={2.065}
              >
                <mesh
                  name='Object_120'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_120.geometry}
                  material={materials["Textura_Hoja1.002"]}
                />
                <mesh
                  name='Object_121'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_121.geometry}
                  material={materials["Textura_Hoja2.002"]}
                />
              </group>
              <group
                name='Plane005_59'
                position={[14.613, 0.442, -9.908]}
                rotation={[0, -1.422, 0]}
                scale={2.065}
              >
                <mesh
                  name='Object_123'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_123.geometry}
                  material={materials.Arbol}
                />
              </group>
              <group
                name='Plane006_60'
                position={[-21.186, 0, -3.193]}
                rotation={[0, 0.833, 0]}
                scale={1.593}
              >
                <mesh
                  name='Object_125'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_125.geometry}
                  material={materials.Arbol}
                />
              </group>
              <group
                name='Plane007_61'
                position={[-16.054, 0.419, 11.946]}
                rotation={[0, 0.625, 0]}
                scale={1.593}
              >
                <mesh
                  name='Object_127'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_127.geometry}
                  material={materials.Arbol}
                />
              </group>
              <group name='Plane004_62' position={[2.876, 0, 0]} scale={29.633}>
                <mesh
                  name='Object_129'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_129.geometry}
                  material={materials.Tierra}
                />
                <mesh
                  name='Object_130'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_130.geometry}
                  material={materials["Llerva.001"]}
                />
                <mesh
                  name='Object_131'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_131.geometry}
                  material={materials["Llerva.001"]}
                />
              </group>
              <group
                name='Cylinder016_63'
                position={[-13.118, 1.313, 16.711]}
                rotation={[0.006, -0.713, -0.005]}
                scale={[0.097, 2.071, 0.097]}
              >
                <mesh
                  name='Object_133'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_133.geometry}
                  material={materials.cercas}
                />
              </group>
              <group
                name='Cube053_64'
                position={[-5.09, -0.06, 14.297]}
                rotation={[0, -1.082, Math.PI]}
                scale={[1.521, 0.6, 1.521]}
              >
                <mesh
                  name='Object_135'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_135.geometry}
                  material={materials.piedras}
                />
              </group>
              <group
                name='Cube062_65'
                position={[14.986, 0, 8.173]}
                rotation={[-Math.PI, -0.092, 0]}
                scale={[1.282, 0.505, 1.282]}
              >
                <mesh
                  name='Object_137'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_137.geometry}
                  material={materials.piedras}
                />
              </group>
              <group
                name='Cube063_66'
                position={[18.351, 0, -7.39]}
                rotation={[-Math.PI, 0, 0]}
                scale={[1.518, 1.215, 1.184]}
              >
                <mesh
                  name='Object_139'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_139.geometry}
                  material={materials.piedras}
                />
              </group>
              <group
                name='Cube066_67'
                position={[-7.252, 0, -9.74]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={[-1.257, 1.006, 0.98]}
              >
                <mesh
                  name='Object_141'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_141.geometry}
                  material={materials.piedras}
                />
              </group>
              <group
                name='Cube067_68'
                position={[2.527, -0.03, 13.044]}
                rotation={[0, 1.555, 0]}
                scale={[2.038, 0.556, 1.816]}
              >
                <mesh
                  name='Object_143'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_143.geometry}
                  material={materials.Piedras_Entrada}
                />
              </group>
              <group
                name='Cube014_69'
                position={[7.711, -14.411, 8.898]}
                rotation={[-Math.PI, -0.092, 0]}
                scale={[1.282, 0.505, 1.282]}
              >
                <mesh
                  name='Object_145'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_145.geometry}
                  material={materials.piedras}
                />
              </group>
              <group
                name='Cube015_70'
                position={[9.224, -6.606, -12.054]}
                rotation={[-Math.PI, -0.092, 0]}
                scale={[1.282, 0.505, 1.282]}
              >
                <mesh
                  name='Object_147'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_147.geometry}
                  material={materials.piedras}
                />
              </group>
              <group
                name='Cube016_71'
                position={[15.691, -9.768, -4.263]}
                rotation={[-Math.PI, -0.092, 0]}
                scale={[1.282, 0.505, 1.282]}
              >
                <mesh
                  name='Object_149'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_149.geometry}
                  material={materials.piedras}
                />
              </group>
              <group
                name='Cube017_72'
                position={[-19.371, -7.565, -4.777]}
                rotation={[2.436, 0.226, -1.465]}
                scale={[1.316, 0.519, 1.316]}
              >
                <mesh
                  name='Object_151'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_151.geometry}
                  material={materials.piedras}
                />
              </group>
              <group
                name='Cube018_73'
                position={[-7.602, -16.592, 10.143]}
                rotation={[-1.388, 0.348, -3.03]}
                scale={[1.316, 0.519, 1.316]}
              >
                <mesh
                  name='Object_153'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_153.geometry}
                  material={materials.piedras}
                />
              </group>
              <group
                name='Empty_74'
                position={[12.301, -0.725, -20.416]}
                scale={3.513}
              />
              <group
                name='Particle_75'
                position={[0.042, 0.007, 0.037]}
                rotation={[-0.76, 0, 1.499]}
              >
                <mesh
                  name='Object_156'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_156.geometry}
                  material={materials["Llerva.001"]}
                />
              </group>
              <group name='Flor1001_76' position={[-35.114, 0, 0]}>
                <mesh
                  name='Object_158'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_158.geometry}
                  material={materials["Flor1.001"]}
                />
              </group>
              <group
                name='metarig_146'
                position={[8.662, 8.482, -0.073]}
                rotation={[0, Math.PI / 2, 0]}
                scale={2.079}
              >
                <group name='GLTF_created_0'>
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name='Object_163'
                    geometry={nodes.Object_163.geometry}
                    material={materials.Camisa}
                    skeleton={nodes.Object_163.skeleton}
                  />
                  <skinnedMesh
                    name='Object_164'
                    geometry={nodes.Object_164.geometry}
                    material={materials.Tela_Chaqueta}
                    skeleton={nodes.Object_164.skeleton}
                  />
                  <skinnedMesh
                    name='Object_166'
                    geometry={nodes.Object_166.geometry}
                    material={materials.Base}
                    skeleton={nodes.Object_166.skeleton}
                  />
                  <skinnedMesh
                    name='Object_168'
                    geometry={nodes.Object_168.geometry}
                    material={materials.Chaqueta}
                    skeleton={nodes.Object_168.skeleton}
                  />
                  <skinnedMesh
                    name='Object_169'
                    geometry={nodes.Object_169.geometry}
                    material={materials.Tela_Chaqueta}
                    skeleton={nodes.Object_169.skeleton}
                  />
                  <skinnedMesh
                    name='Object_171'
                    geometry={nodes.Object_171.geometry}
                    material={materials.Pantalon}
                    skeleton={nodes.Object_171.skeleton}
                  />
                  <skinnedMesh
                    name='Object_173'
                    geometry={nodes.Object_173.geometry}
                    material={materials.Pelo}
                    skeleton={nodes.Object_173.skeleton}
                  />
                  <skinnedMesh
                    name='Object_175'
                    geometry={nodes.Object_175.geometry}
                    material={materials.Shoes}
                    skeleton={nodes.Object_175.skeleton}
                  />
                  <group name='Cylinder000_140' />
                  <group name='Cylinder001_141' />
                  <group name='Cylinder003_142' />
                  <group name='Cylinder004_143' />
                  <group name='Icosphere020_144' />
                  <group name='Zapato_1_145' />
                </group>
              </group>
              <group name='Cube004_147' position={[9.484, 6.422, -4.971]}>
                <mesh
                  name='Object_240'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_240.geometry}
                  material={materials.Textura_Hoja1}
                />
                <mesh
                  name='Object_241'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_241.geometry}
                  material={materials.Textura_Hoja2}
                />
                <mesh
                  name='Object_242'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_242.geometry}
                  material={materials.Flor2}
                />
              </group>
              <group name='Cube013_148' position={[10.881, 0.853, -0.184]}>
                <mesh
                  name='Object_244'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_244.geometry}
                  material={materials["Textura_Hoja1.001"]}
                />
                <mesh
                  name='Object_245'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_245.geometry}
                  material={materials["Textura_Hoja2.001"]}
                />
                <mesh
                  name='Object_246'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_246.geometry}
                  material={materials["Flor1.001"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/diorame/novo1.glb");

export default Hero3D;
