/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Shadow (https://sketchfab.com/jaydenelizondo7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-astronaut-2898a4b265d943919ca830e7d746ac13
Title: Little-astronaut
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Astronaut = ({ aNum, ...props }) => {
  const [currentAnimation, setCurrentAnimation] = useState(null);
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/aboutModels/little-astronaut.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions && aNum >= 0 && aNum < animations.length) {
      if (currentAnimation) {
        currentAnimation.stop();
      }

      const newAction = actions[Object.keys(actions)[aNum]];

      if (newAction) {
        newAction.reset().play();
        setCurrentAnimation(newAction);
      }
    }
  }, [aNum, actions, animations.length]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name='astronautfbx'
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name='Object_2'>
              <group name='RootNode'>
                <group
                  name='Astronaut'
                  position={[0, 76.083, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name='Armature'
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name='Object_6'>
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name='Object_9'
                      geometry={nodes.Object_9.geometry}
                      material={materials.Astronaut}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <group
                      name='Object_8'
                      position={[0, 76.083, 0]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/aboutModels/little-astronaut.glb");

export default Astronaut;
