/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nikita Kravchenko (https://sketchfab.com/NicKravchenko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/daily-space-energy-station-074a437e61554374ba0be856b825374a
Title: Daily space energy station
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const EnergyStation = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/aboutModels/energy_station.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      // console.log(actions);
      const action = actions[Object.keys(actions)[0]];
      action.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group
          name='Sketchfab_model'
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.002}
        >
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group
                name='Cube074_1'
                position={[766.944, -163.547, -499.09]}
                rotation={[-0.051, 0.388, 0.187]}
                scale={1.084}
              >
                <mesh
                  name='Object_4'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.BlueLight}
                />
                <mesh
                  name='Object_5'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials.GreenLight}
                />
              </group>
              <group
                name='Cube075_2'
                position={[714.843, -182.963, -223.003]}
                rotation={[0.087, -0.011, 0.141]}
              >
                <mesh
                  name='Object_7'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_7.geometry}
                  material={materials.Metal1}
                />
              </group>
              <group
                name='Cube076_3'
                position={[783.923, -206.574, -351.062]}
                rotation={[-0.382, -0.357, -0.245]}
              >
                <mesh
                  name='Object_9'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={materials.Metal1}
                />
              </group>
              <group
                name='Cylinder025_4'
                position={[784.264, -157.111, -460.801]}
                rotation={[0.086, -0.123, 0.35]}
              >
                <mesh
                  name='Object_11'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.Metal3}
                />
              </group>
              <group
                name='Cylinder027_5'
                position={[682.595, -137.245, -209.337]}
              >
                <mesh
                  name='Object_13'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.Hoose}
                />
                <mesh
                  name='Object_14'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.Sucker_lightViolet}
                />
              </group>
              <group name='Sphere_7'>
                <mesh
                  name='Object_16'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.material}
                />
              </group>
              <group name='Cube006_9' position={[588.814, 18.612, 236.302]}>
                <mesh
                  name='Object_18'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.Metal3}
                />
                <mesh
                  name='Object_19'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.Sucker_lightViolet}
                />
              </group>
              <group name='Cube010_12' position={[521.162, -116.053, -251.07]}>
                <mesh
                  name='Object_21'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials.Metal1}
                />
                <mesh
                  name='Object_22'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.Sucker_lightViolet}
                />
                <mesh
                  name='Object_23'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group name='Cube015_13' position={[596.073, -166.62, -306.639]}>
                <mesh
                  name='Object_25'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.Metal2}
                />
              </group>
              <group
                name='Cylinder016_16'
                position={[612.548, -87.06, -266.94]}
                rotation={[0, -1.177, 0]}
              >
                <mesh
                  name='Object_27'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials.Metal3}
                />
                <mesh
                  name='Object_28'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.BlueLight}
                />
                <group
                  name='Cube016_15'
                  position={[60.849, -41.857, -0.241]}
                  rotation={[0, 0.862, 0]}
                >
                  <mesh
                    name='Object_30'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_30.geometry}
                    material={materials.Metal4}
                  />
                  <mesh
                    name='Object_31'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_31.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_32'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={materials.Sucker_lightViolet}
                  />
                  <group name='Cylinder017_14' position={[0, 38.939, 0]}>
                    <mesh
                      name='Object_34'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_34.geometry}
                      material={materials.Metal3}
                    />
                    <mesh
                      name='Object_35'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_35.geometry}
                      material={materials.Metal1}
                    />
                    <mesh
                      name='Object_36'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_36.geometry}
                      material={materials.Lepestki}
                    />
                    <mesh
                      name='Object_37'
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_37.geometry}
                      material={materials.RedLight}
                    />
                  </group>
                </group>
              </group>
              <group
                name='Cylinder018_17'
                position={[598.588, -87.06, -300.58]}
                rotation={[0, -1.177, 0]}
              >
                <mesh
                  name='Object_39'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_39.geometry}
                  material={materials.Metal2}
                />
                <mesh
                  name='Object_40'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.BlueLight}
                />
              </group>
              <group
                name='Cylinder020_18'
                position={[609.662, -87.06, -273.893]}
                rotation={[0, -1.177, 0]}
              >
                <mesh
                  name='Object_42'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.Metal1}
                />
                <mesh
                  name='Object_43'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_43.geometry}
                  material={materials.Sucker_lightViolet}
                />
              </group>
              <group name='Cube012_19' position={[497.96, -116.053, -251.07]}>
                <mesh
                  name='Object_45'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_45.geometry}
                  material={materials.GreenLight}
                />
              </group>
              <group name='Cube049_20' position={[520.59, -116.053, -251.07]}>
                <mesh
                  name='Object_47'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_47.geometry}
                  material={materials.Sucker_lightViolet}
                />
              </group>
              <group name='Cube050_21' position={[664.426, -145.713, -189.802]}>
                <mesh
                  name='Object_49'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_49.geometry}
                  material={materials.GreenLight}
                />
              </group>
              <group
                name='Cube051_22'
                position={[682.355, -145.709, -198.779]}
                rotation={[0, Math.PI / 2, 0]}
              >
                <mesh
                  name='Object_51'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_51.geometry}
                  material={materials.Sucker_lightViolet}
                />
              </group>
              <group
                name='Cube052_23'
                position={[682.355, -145.709, -219.095]}
                rotation={[0, Math.PI / 2, 0]}
              >
                <mesh
                  name='Object_53'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_53.geometry}
                  material={materials.Sucker_lightViolet}
                />
              </group>
              <group
                name='Cube053_24'
                position={[597.238, -145.709, -219.095]}
                rotation={[0, -Math.PI / 2, 0]}
              >
                <mesh
                  name='Object_55'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_55.geometry}
                  material={materials.Sucker_lightViolet}
                />
              </group>
              <group
                name='Cube054_25'
                position={[597.238, -145.709, -198.779]}
                rotation={[0, -Math.PI / 2, 0]}
              >
                <mesh
                  name='Object_57'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_57.geometry}
                  material={materials.Sucker_lightViolet}
                />
              </group>
              <group
                name='Cylinder008_26'
                position={[682.182, -137.245, -209.337]}
                scale={0.423}
              >
                <mesh
                  name='Object_59'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_59.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group
                name='Cylinder007_27'
                position={[596.073, -87.06, -306.639]}
              >
                <mesh
                  name='Object_61'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_61.geometry}
                  material={materials.Metal1}
                />
                <mesh
                  name='Object_62'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials.Metal2}
                />
              </group>
              <group
                name='Cylinder014_30'
                position={[596.073, -87.06, -306.639]}
                rotation={[0, -1.177, 0]}
              >
                <mesh
                  name='Object_64'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.Metal4}
                />
                <mesh
                  name='Object_65'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_65.geometry}
                  material={materials.Sucker_light_Circle}
                />
                <group name='Cylinder019_29' position={[6.56, 0, 0]}>
                  <mesh
                    name='Object_67'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_67.geometry}
                    material={materials.Metal4}
                  />
                </group>
              </group>
              <group
                name='Cylinder026_31'
                position={[713.764, -175.779, -220.958]}
                rotation={[0.048, 0.372, 1.972]}
                scale={0.423}
              >
                <mesh
                  name='Object_69'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_69.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group
                name='Cylinder028_32'
                position={[719.025, -189.416, -223.55]}
                rotation={[0.231, -0.231, -1.178]}
                scale={0.423}
              >
                <mesh
                  name='Object_71'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_71.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group
                name='Cylinder029_33'
                position={[781.237, -212.826, -349.071]}
                rotation={[-0.306, -0.035, -1.789]}
                scale={0.423}
              >
                <mesh
                  name='Object_73'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_73.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group
                name='Cylinder030_34'
                position={[785.989, -199.788, -351.808]}
                rotation={[2.749, 0.494, -1.309]}
                scale={0.423}
              >
                <mesh
                  name='Object_75'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_75.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group
                name='Cylinder031_35'
                position={[783.829, -156.151, -460.712]}
                rotation={[-2.781, 0.902, -2.012]}
                scale={[0.182, 0.138, 0.138]}
              >
                <mesh
                  name='Object_77'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_77.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group name='Cube002_36' position={[537.13, -36.375, 230.076]}>
                <mesh
                  name='Object_79'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_79.geometry}
                  material={materials.Metal4}
                />
                <mesh
                  name='Object_80'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_80.geometry}
                  material={materials.BlueLight}
                />
              </group>
              <group
                name='Cube018_37'
                position={[602.575, -18.634, 269.2]}
                rotation={[1.313, 0, 0]}
              >
                <mesh
                  name='Object_82'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={materials.Metal3}
                />
                <mesh
                  name='Object_83'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_83.geometry}
                  material={materials.RedLight}
                />
              </group>
              <group
                name='Cube029_38'
                position={[598.249, -175.012, 128.075]}
                rotation={[-1.839, -0.648, 1.914]}
                scale={0.64}
              >
                <mesh
                  name='Object_85'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_85.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube030_41'
                position={[603.675, -67.901, 270.345]}
                rotation={[-2.256, 1.516, 2.301]}
              >
                <mesh
                  name='Object_87'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_87.geometry}
                  material={materials.Rock}
                />
                <group
                  name='Cube017_39'
                  position={[3.355, 1.937, 1.023]}
                  rotation={[0, -1.493, 0]}
                >
                  <mesh
                    name='Object_89'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_89.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_90'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_90.geometry}
                    material={materials.Metal1}
                  />
                </group>
                <group
                  name='Cylinder021_40'
                  position={[3.355, 49.168, 1.023]}
                  rotation={[0, -1.493, 0]}
                >
                  <mesh
                    name='Object_92'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_92.geometry}
                    material={materials.Metal1}
                  />
                </group>
              </group>
              <group
                name='Cube031_42'
                position={[587.74, -97.636, 269.054]}
                rotation={[0.617, 0.069, -2.631]}
                scale={0.301}
              >
                <mesh
                  name='Object_94'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube032_43'
                position={[596.136, -82.138, 277.788]}
                rotation={[-1.009, -1.401, 0.059]}
                scale={0.301}
              >
                <mesh
                  name='Object_96'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_96.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube033_44'
                position={[604.276, -85.949, 256.474]}
                rotation={[-0.43, -0.682, 1.493]}
                scale={0.301}
              >
                <mesh
                  name='Object_98'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_98.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube034_45'
                position={[614.343, -90.132, 274.296]}
                rotation={[-0.506, -0.12, -0.102]}
                scale={0.15}
              >
                <mesh
                  name='Object_100'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube035_46'
                position={[569.266, -189.255, 159.176]}
                rotation={[0.575, 0.151, -2.509]}
                scale={1.286}
              >
                <mesh
                  name='Object_102'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_102.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube036_47'
                position={[510.241, -159.185, 113.802]}
                rotation={[-0.801, -0.316, -0.245]}
                scale={1.286}
              >
                <mesh
                  name='Object_104'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_104.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube037_48'
                position={[582.032, -191.316, 47.19]}
                rotation={[-0.022, -0.883, 2.092]}
                scale={1.286}
              >
                <mesh
                  name='Object_106'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube038_49'
                position={[604.336, -202.25, 119.154]}
                rotation={[-0.506, -0.12, -0.102]}
                scale={0.639}
              >
                <mesh
                  name='Object_108'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_108.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube039_50'
                position={[693.371, -193.762, 172.192]}
                rotation={[0.541, 0.46, -1.917]}
                scale={1.286}
              >
                <mesh
                  name='Object_110'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_110.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube040_51'
                position={[627.981, -198.084, 125.798]}
                rotation={[-0.349, -0.715, 0.341]}
                scale={1.286}
              >
                <mesh
                  name='Object_112'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_112.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube041_52'
                position={[696.974, -157.629, 66.653]}
                rotation={[0.766, -0.677, 2.966]}
                scale={1.286}
              >
                <mesh
                  name='Object_114'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_114.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube042_53'
                position={[516.491, -196.128, 130.787]}
                rotation={[-0.169, -0.194, -0.884]}
                scale={0.592}
              >
                <mesh
                  name='Object_116'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_116.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube043_54'
                position={[614.901, -223.71, 172.821]}
                rotation={[2.745, -0.916, 2.998]}
                scale={0.731}
              >
                <mesh
                  name='Object_118'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_118.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube013_55'
                position={[599.756, -253.309, 112.603]}
                rotation={[0.19, -0.919, 0.7]}
                scale={1.286}
              >
                <mesh
                  name='Object_120'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_120.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube014_56'
                position={[668.55, -249.667, 27.927]}
                rotation={[-0.321, 1.102, -0.017]}
                scale={1.286}
              >
                <mesh
                  name='Object_122'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_122.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube046_57'
                position={[678.37, -102.212, 16.827]}
                rotation={[3.101, -0.35, 1.672]}
                scale={1.286}
              >
                <mesh
                  name='Object_124'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube047_58'
                position={[633.527, -188.27, -202.19]}
                rotation={[3.091, 1.329, -0.304]}
                scale={2.383}
              >
                <mesh
                  name='Object_126'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_126.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube048_89'
                position={[853.59, -255.399, -452.333]}
                rotation={[-1.359, -0.686, 2.153]}
                scale={0.519}
              >
                <mesh
                  name='Object_128'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_128.geometry}
                  material={materials.Rock}
                />
                <group
                  name='Cube001_59'
                  position={[8.025, -14.883, 237.2]}
                  rotation={[-1.467, -1.077, 2.789]}
                  scale={1.927}
                >
                  <mesh
                    name='Object_130'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_130.geometry}
                    material={materials.Metal1}
                  />
                  <mesh
                    name='Object_131'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_131.geometry}
                    material={materials.Metal2}
                  />
                </group>
                <group
                  name='Cube044_60'
                  position={[-7.48, -38.105, 229.515]}
                  rotation={[2.063, -1.061, 0.269]}
                  scale={1.927}
                >
                  <mesh
                    name='Object_133'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_133.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_134'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_134.geometry}
                    material={materials.Metal1}
                  />
                  <mesh
                    name='Object_135'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_135.geometry}
                    material={materials.BlueLight}
                  />
                </group>
                <group
                  name='Cube045_61'
                  position={[59.383, -1.664, 241.083]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={1.927}
                >
                  <mesh
                    name='Object_137'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_137.geometry}
                    material={materials.Metal3}
                  />
                </group>
                <group
                  name='Cube057_62'
                  position={[-52.068, 50.168, 23.382]}
                  rotation={[-1.164, -1.047, -0.633]}
                  scale={1.522}
                >
                  <mesh
                    name='Object_139'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_139.geometry}
                    material={materials.Rock}
                  />
                </group>
                <group
                  name='Cube058_63'
                  position={[57.697, -28.844, 11.771]}
                  rotation={[-0.991, -0.332, -1.415]}
                  scale={1.522}
                >
                  <mesh
                    name='Object_141'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_141.geometry}
                    material={materials.Rock}
                  />
                </group>
                <group
                  name='Cube059_64'
                  position={[45.03, 99.186, 115.96]}
                  rotation={[-0.523, -0.517, -3.064]}
                  scale={1.522}
                >
                  <mesh
                    name='Object_143'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_143.geometry}
                    material={materials.Rock}
                  />
                </group>
                <group
                  name='Cube060_65'
                  position={[105.373, 52.849, 12.228]}
                  rotation={[2.991, -0.504, 0.006]}
                  scale={1.522}
                >
                  <mesh
                    name='Object_145'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_145.geometry}
                    material={materials.Rock}
                  />
                </group>
                <group
                  name='Cube061_66'
                  position={[87.193, -124.038, -31.861]}
                  rotation={[-1.99, -0.521, -0.718]}
                  scale={1.522}
                >
                  <mesh
                    name='Object_147'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_147.geometry}
                    material={materials.Rock}
                  />
                </group>
                <group
                  name='Cube062_67'
                  position={[155.678, 16.528, 133.457]}
                  rotation={[2.876, -0.189, 1.002]}
                  scale={1.522}
                >
                  <mesh
                    name='Object_149'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_149.geometry}
                    material={materials.Rock}
                  />
                </group>
                <group
                  name='Cube068_68'
                  position={[52.796, -9.333, 250.068]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={3.317}
                >
                  <mesh
                    name='Object_151'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_151.geometry}
                    material={materials.Glass}
                  />
                </group>
                <group
                  name='Cube069_69'
                  position={[9.082, -60.518, 224.447]}
                  rotation={[1.66, 1.104, 0.219]}
                  scale={1.927}
                >
                  <mesh
                    name='Object_153'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_153.geometry}
                    material={materials.Metal1}
                  />
                  <mesh
                    name='Object_154'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_154.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_155'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_155.geometry}
                    material={materials.BlueLight}
                  />
                  <mesh
                    name='Object_156'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_156.geometry}
                    material={materials.Metal4}
                  />
                </group>
                <group
                  name='Cube070_70'
                  position={[40.817, -91.549, 213.066]}
                  rotation={[-1.503, 1.397, -2.775]}
                  scale={1.927}
                >
                  <mesh
                    name='Object_158'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_158.geometry}
                    material={materials.Metal1}
                  />
                  <mesh
                    name='Object_159'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_159.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_160'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_160.geometry}
                    material={materials.BlueLight}
                  />
                  <mesh
                    name='Object_161'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_161.geometry}
                    material={materials.Metal4}
                  />
                </group>
                <group
                  name='Cube071_71'
                  position={[79.046, -61.181, 220.881]}
                  rotation={[-1.99, -1.44, 2.186]}
                  scale={1.927}
                >
                  <mesh
                    name='Object_163'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_163.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_164'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_164.geometry}
                    material={materials.Lepestki}
                  />
                  <mesh
                    name='Object_165'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_165.geometry}
                    material={materials.BlueLight}
                  />
                </group>
                <group
                  name='Cube073_72'
                  position={[106.588, -57.568, 214.223]}
                  rotation={[-1.99, -1.44, 2.186]}
                  scale={2.089}
                >
                  <mesh
                    name='Object_167'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_167.geometry}
                    material={materials.Metal5}
                  />
                </group>
                <group
                  name='Cylinder009_73'
                  position={[12.732, -3.655, 246.059]}
                  rotation={[-1.269, -1.033, 2.954]}
                  scale={[1.466, 1.612, 1.466]}
                >
                  <mesh
                    name='Object_169'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_169.geometry}
                    material={materials.Metal1}
                  />
                  <mesh
                    name='Object_170'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_170.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_171'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_171.geometry}
                    material={materials.Sucker_lightViolet}
                  />
                </group>
                <group
                  name='Cylinder010_74'
                  position={[52.811, -9.277, 250.001]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={1.927}
                >
                  <mesh
                    name='Object_173'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_173.geometry}
                    material={materials.Metal3}
                  />
                  <mesh
                    name='Object_174'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_174.geometry}
                    material={materials.material_15}
                  />
                </group>
                <group
                  name='Cylinder011_75'
                  position={[52.811, -9.277, 250.001]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={1.927}
                >
                  <mesh
                    name='Object_176'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_176.geometry}
                    material={materials.Metal3}
                  />
                </group>
                <group
                  name='Cylinder012_76'
                  position={[59.65, -12.404, 248.99]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={1.927}
                >
                  <mesh
                    name='Object_178'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_178.geometry}
                    material={materials.Wood}
                  />
                </group>
                <group
                  name='Cylinder013_77'
                  position={[53.801, -15.052, 245.499]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={1.391}
                >
                  <mesh
                    name='Object_180'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_180.geometry}
                    material={materials.Wood}
                  />
                </group>
                <group
                  name='Cylinder022_78'
                  position={[44.905, -10.012, 247.779]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={1.699}
                >
                  <mesh
                    name='Object_182'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_182.geometry}
                    material={materials.Wood}
                  />
                </group>
                <group
                  name='Cylinder023_79'
                  position={[53.855, -9.939, 249.79]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={2.113}
                >
                  <mesh
                    name='Object_184'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_184.geometry}
                    material={materials.Wood}
                  />
                </group>
                <group
                  name='Cylinder024_80'
                  position={[52.63, -3.854, 254.617]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={1.447}
                >
                  <mesh
                    name='Object_186'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_186.geometry}
                    material={materials.Wood}
                  />
                </group>
                <group
                  name='Icosphere_81'
                  position={[58.967, -15.008, 251.694]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={1.927}
                >
                  <mesh
                    name='Object_188'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_188.geometry}
                    material={materials.GreenLeavs}
                  />
                </group>
                <group
                  name='Icosphere001_82'
                  position={[53.309, -16.932, 247.451]}
                  rotation={[-1.206, -1.097, 2.772]}
                  scale={1.391}
                >
                  <mesh
                    name='Object_190'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_190.geometry}
                    material={materials.GreenLeavs}
                  />
                </group>
                <group
                  name='Icosphere002_83'
                  position={[43.68, -11.814, 250.542]}
                  rotation={[-0.719, -1.002, -2.973]}
                  scale={1.699}
                >
                  <mesh
                    name='Object_192'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_192.geometry}
                    material={materials.GreenLeavs}
                  />
                </group>
                <group
                  name='Icosphere003_84'
                  position={[52.331, -12.18, 253.226]}
                  rotation={[-0.719, -1.002, -2.973]}
                  scale={2.113}
                >
                  <mesh
                    name='Object_194'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_194.geometry}
                    material={materials.GreenLeavs}
                  />
                </group>
                <group
                  name='Icosphere004_85'
                  position={[51.586, -5.389, 256.97]}
                  rotation={[-0.719, -1.002, -2.973]}
                  scale={1.447}
                >
                  <mesh
                    name='Object_196'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_196.geometry}
                    material={materials.GreenLeavs}
                  />
                </group>
                <group
                  name='Icosphere005_86'
                  position={[57.978, -6.235, 251.282]}
                  rotation={[-0.719, -1.002, -2.973]}
                  scale={2.113}
                >
                  <mesh
                    name='Object_198'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_198.geometry}
                    material={materials.GreenLeavs}
                  />
                </group>
                <group
                  name='Icosphere006_87'
                  position={[54.124, -6.775, 249.991]}
                  rotation={[-0.719, -1.002, -2.973]}
                  scale={2.113}
                >
                  <mesh
                    name='Object_200'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_200.geometry}
                    material={materials.GreenLeavs}
                  />
                </group>
                <group
                  name='Icosphere007_88'
                  position={[56.468, -8.733, 248.863]}
                  rotation={[-0.719, -1.002, -2.973]}
                  scale={2.113}
                >
                  <mesh
                    name='Object_202'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_202.geometry}
                    material={materials.GreenLeavs}
                  />
                </group>
              </group>
              <group
                name='Cube003_90'
                position={[609.218, -184.953, -315.972]}
                rotation={[0.335, -1.28, -2.902]}
                scale={1.286}
              >
                <mesh
                  name='Object_204'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_204.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube007_91'
                position={[666.567, -189.818, -332.401]}
                rotation={[-0.771, 0.749, 0.765]}
                scale={0.508}
              >
                <mesh
                  name='Object_206'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_206.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube008_92'
                position={[659.442, -194.097, -284.082]}
                rotation={[1.234, -0.18, -3.082]}
                scale={0.508}
              >
                <mesh
                  name='Object_208'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_208.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube009_93'
                position={[705.36, -190.15, -288.413]}
                rotation={[2.892, 1.111, 1.096]}
                scale={0.508}
              >
                <mesh
                  name='Object_210'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_210.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube011_94'
                position={[620.824, -168.836, -300.819]}
                rotation={[-0.105, 1.133, 0.174]}
                scale={0.313}
              >
                <mesh
                  name='Object_212'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_212.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube055_95'
                position={[589.136, -72.024, 255.296]}
                rotation={[2.443, 0.292, -2.656]}
                scale={0.301}
              >
                <mesh
                  name='Object_214'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_214.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube056_96'
                position={[615.379, -78.195, 279.11]}
                rotation={[-0.705, -0.006, -2.78]}
                scale={0.301}
              >
                <mesh
                  name='Object_216'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_216.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube063_97'
                position={[737.19, -256.547, -412.744]}
                rotation={[-0.196, 0.036, 1.98]}
                scale={0.79}
              >
                <mesh
                  name='Object_218'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_218.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube064_98'
                position={[683.541, -260.712, -362.19]}
                rotation={[2.351, 1.408, -2.813]}
                scale={0.79}
              >
                <mesh
                  name='Object_220'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_220.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube065_99'
                position={[663.14, -239.132, -315.67]}
                rotation={[1.578, 0.68, -2.236]}
                scale={0.79}
              >
                <mesh
                  name='Object_222'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_222.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube066_100'
                position={[536.769, -221.689, -32.421]}
                rotation={[-1.36, 0.655, -1.389]}
                scale={2.383}
              >
                <mesh
                  name='Object_224'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_224.geometry}
                  material={materials.Rock}
                />
              </group>
              <group
                name='Cube067_101'
                position={[605.892, -240.1, 2.799]}
                rotation={[0.771, 0.384, -0.266]}
                scale={2.383}
              >
                <mesh
                  name='Object_226'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_226.geometry}
                  material={materials.Rock}
                />
              </group>
              <group name='Cylinder_110' position={[56.194, 0, 0]}>
                <mesh
                  name='Object_228'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_228.geometry}
                  material={materials.Metal1}
                />
                <mesh
                  name='Object_229'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_229.geometry}
                  material={materials.Metal2}
                />
                <mesh
                  name='Object_230'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_230.geometry}
                  material={materials.Metal3}
                />
                <mesh
                  name='Object_231'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_231.geometry}
                  material={materials.Sucker_lightViolet}
                />
                <group
                  name='Cube019_102'
                  position={[0, 0, 90.007]}
                  rotation={[Math.PI / 2, 0, 0.916]}
                >
                  <mesh
                    name='Object_233'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_233.geometry}
                    material={materials.Lepestki}
                  />
                  <mesh
                    name='Object_234'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_234.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_235'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_235.geometry}
                    material={materials.OrangeLight}
                  />
                  <mesh
                    name='Object_236'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_236.geometry}
                    material={materials.Metal1}
                  />
                </group>
                <group
                  name='Cube020_103'
                  position={[0, 63.645, 63.645]}
                  rotation={[Math.PI / 4, 0, 0.916]}
                >
                  <mesh
                    name='Object_238'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_238.geometry}
                    material={materials.Lepestki}
                  />
                  <mesh
                    name='Object_239'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_239.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_240'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_240.geometry}
                    material={materials.Metal1}
                  />
                  <mesh
                    name='Object_241'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_241.geometry}
                    material={materials.OrangeLight}
                  />
                </group>
                <group
                  name='Cube021_104'
                  position={[0, 90.007, 0]}
                  rotation={[0, 0, 0.916]}
                >
                  <mesh
                    name='Object_243'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_243.geometry}
                    material={materials.Lepestki}
                  />
                  <mesh
                    name='Object_244'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_244.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_245'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_245.geometry}
                    material={materials.OrangeLight}
                  />
                  <mesh
                    name='Object_246'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_246.geometry}
                    material={materials.Metal1}
                  />
                </group>
                <group
                  name='Cube022_105'
                  position={[0, -63.645, 63.645]}
                  rotation={[2.356, 0, 0.916]}
                >
                  <mesh
                    name='Object_248'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_248.geometry}
                    material={materials.Lepestki}
                  />
                  <mesh
                    name='Object_249'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_249.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_250'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_250.geometry}
                    material={materials.Metal1}
                  />
                  <mesh
                    name='Object_251'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_251.geometry}
                    material={materials.OrangeLight}
                  />
                </group>
                <group
                  name='Cube023_106'
                  position={[0, -90.007, 0]}
                  rotation={[-Math.PI, 0, 0.916]}
                >
                  <mesh
                    name='Object_253'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_253.geometry}
                    material={materials.Lepestki}
                  />
                  <mesh
                    name='Object_254'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_254.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_255'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_255.geometry}
                    material={materials.OrangeLight}
                  />
                  <mesh
                    name='Object_256'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_256.geometry}
                    material={materials.Metal1}
                  />
                </group>
                <group
                  name='Cube024_107'
                  position={[0, -63.645, -63.645]}
                  rotation={[-2.356, 0, 0.916]}
                >
                  <mesh
                    name='Object_258'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_258.geometry}
                    material={materials.Lepestki}
                  />
                  <mesh
                    name='Object_259'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_259.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_260'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_260.geometry}
                    material={materials.Metal1}
                  />
                  <mesh
                    name='Object_261'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_261.geometry}
                    material={materials.OrangeLight}
                  />
                </group>
                <group
                  name='Cube025_108'
                  position={[0, 0, -90.007]}
                  rotation={[-Math.PI / 2, 0, 0.916]}
                >
                  <mesh
                    name='Object_263'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_263.geometry}
                    material={materials.Lepestki}
                  />
                  <mesh
                    name='Object_264'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_264.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_265'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_265.geometry}
                    material={materials.OrangeLight}
                  />
                  <mesh
                    name='Object_266'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_266.geometry}
                    material={materials.Metal1}
                  />
                </group>
                <group
                  name='Cube026_109'
                  position={[0, 63.645, -63.645]}
                  rotation={[-Math.PI / 4, 0, 0.916]}
                >
                  <mesh
                    name='Object_268'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_268.geometry}
                    material={materials.Lepestki}
                  />
                  <mesh
                    name='Object_269'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_269.geometry}
                    material={materials.Metal2}
                  />
                  <mesh
                    name='Object_270'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_270.geometry}
                    material={materials.Metal1}
                  />
                  <mesh
                    name='Object_271'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_271.geometry}
                    material={materials.OrangeLight}
                  />
                </group>
              </group>
              <group name='Cylinder001_111' position={[56.194, 0, 0]}>
                <mesh
                  name='Object_273'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_273.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group name='Cylinder003_112' position={[56.194, 0, 0]}>
                <mesh
                  name='Object_275'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_275.geometry}
                  material={materials.Metal2}
                />
                <mesh
                  name='Object_276'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_276.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group name='Cylinder002_113'>
                <mesh
                  name='Object_278'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_278.geometry}
                  material={materials.Sucker}
                />
                <mesh
                  name='Object_279'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_279.geometry}
                  material={materials.Metal2}
                />
                <mesh
                  name='Object_280'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_280.geometry}
                  material={materials.Sucker_lightViolet}
                />
              </group>
              <group name='Cylinder004_114' position={[85.888, 0, 115.875]}>
                <mesh
                  name='Object_282'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_282.geometry}
                  material={materials.Metal2}
                />
                <mesh
                  name='Object_283'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_283.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group name='Plane_115' position={[199.333, 0, 0]}>
                <mesh
                  name='Object_285'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_285.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group name='Cylinder006_116' position={[199.642, 0, 0]}>
                <mesh
                  name='Object_287'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_287.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group name='Sun001_117' position={[-1244.537, 0, 0]} scale={3}>
                <mesh
                  name='Object_289'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_289.geometry}
                  material={materials.Sun1}
                />
              </group>
              <group
                name='Plane001_118'
                position={[-262.624, 30.836, 40.146]}
                rotation={[-3.019, -0.15, -3.105]}
                scale={5.018}
              >
                <mesh
                  name='Object_291'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_291.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane002_119'
                position={[2.767, -42.528, -23.419]}
                rotation={[-2.156, 0.409, -2.668]}
                scale={5.018}
              >
                <mesh
                  name='Object_293'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_293.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane003_120'
                position={[-298.792, -129.753, 218.895]}
                rotation={[-0.203, 1.17, 0.916]}
                scale={5.018}
              >
                <mesh
                  name='Object_295'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_295.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane004_121'
                position={[-163.083, -54.123, 27.308]}
                rotation={[-2.552, 0.197, -2.303]}
                scale={5.018}
              >
                <mesh
                  name='Object_297'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_297.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane005_122'
                position={[-235.096, -35.745, 170.728]}
                rotation={[-3.086, 1.365, -2.727]}
                scale={5.018}
              >
                <mesh
                  name='Object_299'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_299.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane006_123'
                position={[-90.44, 29.337, 202.794]}
                rotation={[-2.421, 1.339, -0.638]}
                scale={5.018}
              >
                <mesh
                  name='Object_301'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_301.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane000_124'
                position={[-248.115, 236.091, -24.48]}
                rotation={[2.978, 1.327, -1.579]}
                scale={5.016}
              >
                <mesh
                  name='Object_303'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_303.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane007_125'
                position={[-355.296, 189.177, -9.594]}
                rotation={[-1.41, 0.779, 2.629]}
                scale={5.016}
              >
                <mesh
                  name='Object_305'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_305.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane008_126'
                position={[-208.104, 150.961, -104.63]}
                rotation={[-0.385, 1.039, 1.189]}
                scale={5.018}
              >
                <mesh
                  name='Object_307'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_307.geometry}
                  material={materials.Sun3}
                />
              </group>
              <group
                name='Plane009_127'
                position={[-281.453, 144.889, -58.738]}
                rotation={[2.602, 1.296, -1.618]}
                scale={5.018}
              >
                <mesh
                  name='Object_309'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_309.geometry}
                  material={materials.Sun3}
                />
              </group>
              <group
                name='Plane010_128'
                position={[-273.652, 145.288, -32.22]}
                rotation={[2.203, 1.053, -1.329]}
                scale={5.018}
              >
                <mesh
                  name='Object_311'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_311.geometry}
                  material={materials.Sun3}
                />
              </group>
              <group
                name='Plane011_129'
                position={[-246.31, 116.571, -15.669]}
                rotation={[2.573, 1.019, -1.806]}
                scale={5.018}
              >
                <mesh
                  name='Object_313'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_313.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane012_130'
                position={[-360.735, -74.235, 61.274]}
                rotation={[-0.061, 0.299, 0.744]}
                scale={5.018}
              >
                <mesh
                  name='Object_315'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_315.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane013_131'
                position={[-446.79, 96.366, -121.068]}
                rotation={[0.058, -0.372, -0.059]}
                scale={5.018}
              >
                <mesh
                  name='Object_317'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_317.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane014_132'
                position={[-268.13, -10.969, -42.075]}
                rotation={[0.427, 1.045, 0.811]}
                scale={5.018}
              >
                <mesh
                  name='Object_319'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_319.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane015_133'
                position={[-373.882, 85.673, -36.536]}
                rotation={[0.428, -0.024, -0.099]}
                scale={5.018}
              >
                <mesh
                  name='Object_321'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_321.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane016_134'
                position={[-499.31, 7.3, 104.019]}
                rotation={[-1.654, -0.588, -2.678]}
                scale={5.018}
              >
                <mesh
                  name='Object_323'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_323.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane017_135'
                position={[-33.732, 169.466, -59.962]}
                rotation={[1.24, 1.009, -0.055]}
                scale={5.016}
              >
                <mesh
                  name='Object_325'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_325.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane018_136'
                position={[-59.587, 156.051, 55.191]}
                rotation={[0.112, 0.671, 1.012]}
                scale={5.018}
              >
                <mesh
                  name='Object_327'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_327.geometry}
                  material={materials.Sun2}
                />
              </group>
              <group
                name='Plane019_137'
                position={[5.853, 26.82, -158.143]}
                rotation={[-0.123, 0.509, 0.106]}
                scale={5.018}
              >
                <mesh
                  name='Object_329'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_329.geometry}
                  material={materials.Sun3}
                />
              </group>
              <group
                name='Plane020_138'
                position={[105.077, 90.92, -61.65]}
                rotation={[0.417, 0.147, 0.069]}
                scale={5.018}
              >
                <mesh
                  name='Object_331'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_331.geometry}
                  material={materials.Sun3}
                />
              </group>
              <group
                name='Plane021_139'
                position={[-58.326, 75.352, -85.349]}
                rotation={[0.541, 0.387, -0.157]}
                scale={5.018}
              >
                <mesh
                  name='Object_333'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_333.geometry}
                  material={materials.Sun3}
                />
              </group>
              <group name='Vagon1_144' position={[537.601, -36.375, 230.076]}>
                <mesh
                  name='Object_335'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_335.geometry}
                  material={materials.Metal2}
                />
                <mesh
                  name='Object_336'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_336.geometry}
                  material={materials.RedLight}
                />
                <mesh
                  name='Object_337'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_337.geometry}
                  material={materials.Lepestki}
                />
                <mesh
                  name='Object_338'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_338.geometry}
                  material={materials.VioletLight}
                />
                <mesh
                  name='Object_339'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_339.geometry}
                  material={materials.Metal4}
                />
                <group name='lEFTeNGINE_140' position={[14.443, 0, -8.952]}>
                  <mesh
                    name='Object_341'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_341.geometry}
                    material={materials.RedLight}
                  />
                </group>
                <group name='lEFTeNGINE001_141' position={[14.443, 0, -10.89]}>
                  <mesh
                    name='Object_343'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_343.geometry}
                    material={materials.RedLight}
                  />
                </group>
                <group
                  name='rIGHTeNGINE_142'
                  position={[14.443, 0, 8.952]}
                  rotation={[-Math.PI, 0, 0]}
                >
                  <mesh
                    name='Object_345'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_345.geometry}
                    material={materials.RedLight}
                  />
                </group>
                <group
                  name='rIGHTeNGINE001_143'
                  position={[14.443, 0, 10.092]}
                  rotation={[-Math.PI, 0, 0]}
                >
                  <mesh
                    name='Object_347'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_347.geometry}
                    material={materials.RedLight}
                  />
                </group>
              </group>
              <group
                name='Gruz1_145'
                position={[545.809, -19.014, 229.576]}
                scale={0}
              >
                <mesh
                  name='Object_349'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_349.geometry}
                  material={materials.OrangeLight}
                />
              </group>
              <group
                name='DoorLeft_146'
                position={[550.526, -23.354, 224.522]}
                rotation={[-0.774, 0, 0]}
              >
                <mesh
                  name='Object_351'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_351.geometry}
                  material={materials.Metal3}
                />
              </group>
              <group
                name='DoorRight_147'
                position={[553.563, -23.354, 235.631]}
                rotation={[-2.367, 0, -Math.PI]}
              >
                <mesh
                  name='Object_353'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_353.geometry}
                  material={materials.Metal3}
                />
              </group>
              <group
                name='Gruz2_148'
                position={[545.905, -18.861, 229.578]}
                scale={0}
              >
                <mesh
                  name='Object_355'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_355.geometry}
                  material={materials.Orange2}
                />
              </group>
              <group
                name='Gruz3_149'
                position={[545.884, -18.897, 229.578]}
                scale={0}
              >
                <mesh
                  name='Object_357'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_357.geometry}
                  material={materials.BlueLight}
                />
              </group>
              <group
                name='Vagon1001_154'
                position={[855.92, -151.29, -54.782]}
                rotation={[-1.571, 1.564, 1.571]}
              >
                <mesh
                  name='Object_359'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_359.geometry}
                  material={materials.Metal2}
                />
                <mesh
                  name='Object_360'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_360.geometry}
                  material={materials.RedLight}
                />
                <mesh
                  name='Object_361'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_361.geometry}
                  material={materials.Lepestki}
                />
                <mesh
                  name='Object_362'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_362.geometry}
                  material={materials.VioletLight}
                />
                <mesh
                  name='Object_363'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_363.geometry}
                  material={materials.Metal4}
                />
                <group name='lEFTeNGINE002_150' position={[14.443, 0, -8.952]}>
                  <mesh
                    name='Object_365'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_365.geometry}
                    material={materials.RedLight}
                  />
                </group>
                <group name='lEFTeNGINE003_151' position={[14.443, 0, -10.89]}>
                  <mesh
                    name='Object_367'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_367.geometry}
                    material={materials.RedLight}
                  />
                </group>
                <group
                  name='rIGHTeNGINE002_152'
                  position={[14.443, 0, 8.952]}
                  rotation={[-Math.PI, 0, 0]}
                >
                  <mesh
                    name='Object_369'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_369.geometry}
                    material={materials.RedLight}
                  />
                </group>
                <group
                  name='rIGHTeNGINE003_153'
                  position={[14.443, 0, 10.092]}
                  rotation={[-Math.PI, 0, 0]}
                >
                  <mesh
                    name='Object_371'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_371.geometry}
                    material={materials.RedLight}
                  />
                </group>
              </group>
              <group
                name='Gruz1001_155'
                position={[854.715, -141.32, -68.772]}
                scale={0.387}
              >
                <mesh
                  name='Object_373'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_373.geometry}
                  material={materials.OrangeLight}
                />
              </group>
              <group
                name='DoorLeft001_156'
                position={[849.6, -141.684, -67.707]}
                rotation={[0.001, 0, 0]}
              >
                <mesh
                  name='Object_375'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_375.geometry}
                  material={materials.Metal3}
                />
              </group>
              <group
                name='DoorRight001_157'
                position={[862.018, -141.755, -70.744]}
                rotation={[-3.122, 0, -Math.PI]}
              >
                <mesh
                  name='Object_377'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_377.geometry}
                  material={materials.Metal3}
                />
              </group>
              <group
                name='Gruz2001_158'
                position={[854.849, -141.708, -62.794]}
                rotation={[0, 0, 1.573]}
                scale={0.387}
              >
                <mesh
                  name='Object_379'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_379.geometry}
                  material={materials.Orange2}
                />
              </group>
              <group
                name='Gruz3001_159'
                position={[855.072, -141.317, -74.948]}
                rotation={[0, 0, 3.134]}
                scale={0.387}
              >
                <mesh
                  name='Object_381'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_381.geometry}
                  material={materials.BlueLight}
                />
              </group>
              <group name='Cube_160' position={[471.846, -9.429, 131.233]}>
                <mesh
                  name='Object_383'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_383.geometry}
                  material={materials.Metal1}
                />
                <mesh
                  name='Object_384'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_384.geometry}
                  material={materials.OrangeLight}
                />
                <mesh
                  name='Object_385'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_385.geometry}
                  material={materials.Metal3}
                />
                <mesh
                  name='Object_386'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_386.geometry}
                  material={materials.Sucker_lightViolet}
                />
                <mesh
                  name='Object_387'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_387.geometry}
                  material={materials.Metal2}
                />
                <mesh
                  name='Object_388'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_388.geometry}
                  material={materials.RedLight}
                />
              </group>
              <group name='Cube028_161' position={[498.119, -10.321, 74.659]}>
                <mesh
                  name='Object_390'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_390.geometry}
                  material={materials.Metal3}
                />
                <mesh
                  name='Object_391'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_391.geometry}
                  material={materials.BlueLight}
                />
              </group>
              <group name='Cylinder005_162' position={[199.642, 0, 0]}>
                <mesh
                  name='Object_393'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_393.geometry}
                  material={materials.Hoose}
                />
                <mesh
                  name='Object_394'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_394.geometry}
                  material={materials.Sucker_light_Circle}
                />
              </group>
              <group name='Cube027_163' position={[498.119, -10.321, 74.659]}>
                <mesh
                  name='Object_396'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_396.geometry}
                  material={materials.GreenLight}
                />
              </group>
              <group name='Cube004_164' position={[471.846, -9.429, 143.718]}>
                <mesh
                  name='Object_398'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_398.geometry}
                  material={materials.Metal2}
                />
              </group>
              <group name='Cube005_165' position={[471.846, -9.429, 117.617]}>
                <mesh
                  name='Object_400'
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_400.geometry}
                  material={materials.Metal2}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/aboutModels/energy_station.glb");
export default EnergyStation;
