/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/space-station-scene-wip-2-test-33b67cd20af34ec3b68dd94a5d94c678
Title: Space station scene Wip 2 (Test)
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

const SpaceStation = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/aboutModels/space_station.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      // console.log(actions);
      const action = actions[Object.keys(actions)[0]];
      action.play();
      action.timeScale = 0.9;
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group name='Root'>
            <group
              name='Circle017'
              position={[83.672, 33.193, 0.089]}
              rotation={[0, 0, -0.696]}
            >
              <mesh
                name='Circle017_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle017_0.geometry}
                material={materials.material_11}
              />
            </group>
            <group name='Circle016' position={[56.482, 60.383, 0.089]}>
              <mesh
                name='Circle016_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle016_0.geometry}
                material={materials.material_11}
              />
            </group>
            <group name='Circle'>
              <mesh
                name='Circle_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle_0.geometry}
                material={materials.material_8}
              />
            </group>
            <group name='Circle001'>
              <mesh
                name='Circle001_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle001_0.geometry}
                material={materials.Material}
              />
            </group>
            <group name='Point' position={[-12.152, -10.184, 18.452]}>
              <group name='Point_1' />
            </group>
            <group
              name='Hemi'
              position={[5.792, 4.847, 18.219]}
              rotation={[0.534, -0.549, 0.148]}
            >
              <group name='Hemi_1' />
            </group>
            <group name='Circle004'>
              <mesh
                name='Circle004_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle004_0.geometry}
                // material={materials.material_9}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
            </group>
            <group name='Circle007' position={[0, 78.137, 0.059]}>
              <mesh
                name='Circle007_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle007_0.geometry}
                // material={materials.door}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group
                name='Circle009'
                position={[0, 1.079, 0.269]}
                rotation={[0, 0, -Math.PI]}
              >
                <mesh
                  name='Circle009_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle009_0.geometry}
                  // material={materials.door}
                  material={
                    new THREE.MeshStandardMaterial({
                      color: new THREE.Color(0xff4c4c),
                      emissive: new THREE.Color(0xff4c4c),
                      emissiveIntensity: 9,
                      roughness: 0.1,
                      metalness: 0.1,
                      transparent: true,
                      opacity: 0.9,
                      depthWrite: false, //efekat "plutanja"
                    })
                  }
                />
              </group>
              <group name='Circle008' position={[0, -0.843, 0.269]}>
                <mesh
                  name='Circle008_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle008_0.geometry}
                  // material={materials.door}
                  material={
                    new THREE.MeshStandardMaterial({
                      color: new THREE.Color(0xff4c4c),
                      emissive: new THREE.Color(0xff4c4c),
                      emissiveIntensity: 9,
                      roughness: 0.1,
                      metalness: 0.1,
                      transparent: true,
                      opacity: 0.9,
                      depthWrite: false, //efekat "plutanja"
                    })
                  }
                />
              </group>
              <group name='Circle006' position={[0, 0, -10.541]}>
                <mesh
                  name='Circle006_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle006_0.geometry}
                  // material={materials.door}
                  material={
                    new THREE.MeshStandardMaterial({
                      color: new THREE.Color(0xff4c4c),
                      emissive: new THREE.Color(0xff4c4c),
                      emissiveIntensity: 9,
                      roughness: 0.1,
                      metalness: 0.1,
                      transparent: true,
                      opacity: 0.9,
                      depthWrite: false, //efekat "plutanja"
                    })
                  }
                />
              </group>
              <group name='Circle005' position={[0, 0, 7.31]}>
                <mesh
                  name='Circle005_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle005_0.geometry}
                  material={materials.door}
                />
              </group>
            </group>
            <group name='Circle018' rotation={[0, 0, -Math.PI]}>
              <mesh
                name='Circle018_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle018_0.geometry}
                // material={materials.material}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
            </group>
            <group name='Circle020'>
              <mesh
                name='Circle020_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle020_0.geometry}
                material={materials.material_8}
              />
            </group>
            <group name='Circle021' rotation={[0, 0, -Math.PI]}>
              <mesh
                name='Circle021_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle021_0.geometry}
                material={materials.material_8}
              />
            </group>
            <group name='Circle022'>
              <mesh
                name='Circle022_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle022_0.geometry}
                material={materials.material_8}
              />
            </group>
            <group name='Circle023'>
              <mesh
                name='Circle023_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle023_0.geometry}
                // material={materials.Root}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
            </group>
            <group name='Sphere001' position={[0, 0, 1.365]}>
              <mesh
                name='Sphere001_0'
                castShadow
                receiveShadow
                geometry={nodes.Sphere001_0.geometry}
                material={materials["Material.011"]}
              />
            </group>
            <group name='Torus000' position={[0, 0, 19.113]}>
              <mesh
                name='Torus000_0'
                castShadow
                receiveShadow
                geometry={nodes.Torus000_0.geometry}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group name='Torus002'>
                <mesh
                  name='Torus002_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus002_0.geometry}
                  // material={materials["Material.014"]}
                  material={
                    new THREE.MeshStandardMaterial({
                      color: new THREE.Color(0xff4c4c),
                      emissive: new THREE.Color(0xff4c4c),
                      emissiveIntensity: 9,
                      roughness: 0.1,
                      metalness: 0.1,
                      transparent: true,
                      opacity: 0.9,
                      depthWrite: false, //efekat "plutanja"
                    })
                  }
                />
                <group name='Torus003'>
                  <mesh
                    name='Torus003_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus003_0.geometry}
                    // material={materials["Material.014"]}
                    material={
                      new THREE.MeshStandardMaterial({
                        color: new THREE.Color(0xff4c4c),
                        emissive: new THREE.Color(0xff4c4c),
                        emissiveIntensity: 9,
                        roughness: 0.1,
                        metalness: 0.1,
                        transparent: true,
                        opacity: 0.9,
                        depthWrite: false, //efekat "plutanja"
                      })
                    }
                  />
                  <group name='Torus004'>
                    <mesh
                      name='Torus004_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.Torus004_0.geometry}
                      // material={materials["Material.014"]}
                      material={
                        new THREE.MeshStandardMaterial({
                          color: new THREE.Color(0xff4c4c),
                          emissive: new THREE.Color(0xff4c4c),
                          emissiveIntensity: 9,
                          roughness: 0.1,
                          metalness: 0.1,
                          transparent: true,
                          opacity: 0.9,
                          depthWrite: false, //efekat "plutanja"
                        })
                      }
                    />
                    <group name='Torus001'>
                      <mesh
                        name='Torus001_0'
                        castShadow
                        receiveShadow
                        geometry={nodes.Torus001_0.geometry}
                        // material={materials["Material.014"]}
                        material={
                          new THREE.MeshStandardMaterial({
                            color: new THREE.Color(0xff0000),
                            emissive: new THREE.Color(0xff0000),
                            emissiveIntensity: 5,
                            roughness: 0.1,
                            metalness: 0.1,
                            transparent: true,
                            opacity: 0.9,
                            depthWrite: false, //efekat "plutanja"
                          })
                        }
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group name='Circle024' rotation={[0, 0, -Math.PI]}>
              <mesh
                name='Circle024_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle024_0.geometry}
                material={materials["Material.013"]}
              />
            </group>
            <group
              name='Circle025'
              position={[0, 0, 38.866]}
              rotation={[Math.PI, 0, -Math.PI]}
            >
              <mesh
                name='Circle025_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle025_0.geometry}
                material={materials["Material.013"]}
              />
            </group>
            <group
              name='Circle010'
              position={[0, -78.137, 0.059]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                name='Circle010_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle010_0.geometry}
                material={materials.door}
              />
              <group name='Circle027' position={[0, 0, 7.31]}>
                <mesh
                  name='Circle027_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle027_0.geometry}
                  material={materials.door}
                />
              </group>
              <group name='Circle026' position={[0, 0, -10.541]}>
                <mesh
                  name='Circle026_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle026_0.geometry}
                  material={materials.door}
                />
              </group>
              <group name='Circle012' position={[0, -0.843, 0.269]}>
                <mesh
                  name='Circle012_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle012_0.geometry}
                  material={materials.door}
                />
              </group>
              <group
                name='Circle011'
                position={[0, 1.079, 0.269]}
                rotation={[0, 0, -Math.PI]}
              >
                <mesh
                  name='Circle011_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle011_0.geometry}
                  material={materials.door}
                />
              </group>
            </group>
            <group name='Cube002' position={[-6.273, -198.587, 6.361]}>
              <mesh
                name='Cube002_0'
                castShadow
                receiveShadow
                geometry={nodes.Cube002_0.geometry}
                // material={materials.material_3}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group name='Torus006'>
                <mesh
                  name='Torus006_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus006_0.geometry}
                  // material={materials.Root}
                  material={
                    new THREE.MeshStandardMaterial({
                      color: new THREE.Color(0xff4c4c),
                      emissive: new THREE.Color(0xff4c4c),
                      emissiveIntensity: 9,
                      roughness: 0.1,
                      metalness: 0.1,
                      transparent: true,
                      opacity: 0.9,
                      depthWrite: false, //efekat "plutanja"
                    })
                  }
                />
                <group name='Torus005' scale={1.602}>
                  <mesh
                    name='Torus005_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus005_0.geometry}
                    material={materials.Root}
                  />
                </group>
              </group>
            </group>
            <group name='Cube003' position={[-12.908, 195.289, 7.823]}>
              <mesh
                name='Cube003_0'
                castShadow
                receiveShadow
                geometry={nodes.Cube003_0.geometry}
                // material={materials.material_3}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group name='Torus007'>
                <mesh
                  name='Torus007_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus007_0.geometry}
                  material={materials.Root}
                />
                <group name='Torus008' scale={1.602}>
                  <mesh
                    name='Torus008_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus008_0.geometry}
                    material={materials.Root}
                  />
                </group>
              </group>
            </group>
            <group name='Cube004' position={[10.331, -153.78, 1.861]}>
              <mesh
                name='Cube004_0'
                castShadow
                receiveShadow
                geometry={nodes.Cube004_0.geometry}
                // material={materials.material_3}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group name='Torus009'>
                <mesh
                  name='Torus009_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus009_0.geometry}
                  material={materials.Root}
                />
                <group name='Torus010' scale={1.602}>
                  <mesh
                    name='Torus010_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus010_0.geometry}
                    material={materials.Root}
                  />
                </group>
              </group>
            </group>
            <group name='Cube005' position={[11.202, 195.027, 9.845]}>
              <mesh
                name='Cube005_0'
                castShadow
                receiveShadow
                geometry={nodes.Cube005_0.geometry}
                // material={materials.material_3}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group name='Torus011'>
                <mesh
                  name='Torus011_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus011_0.geometry}
                  material={materials.Root}
                />
                <group name='Torus012' scale={1.602}>
                  <mesh
                    name='Torus012_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus012_0.geometry}
                    material={materials.Root}
                  />
                </group>
              </group>
            </group>
            <group name='Cube006' position={[3.88, -182.278, 12.477]}>
              <mesh
                name='Cube006_0'
                castShadow
                receiveShadow
                geometry={nodes.Cube006_0.geometry}
                // material={materials.material_3}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group name='Torus013'>
                <mesh
                  name='Torus013_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus013_0.geometry}
                  material={materials.Root}
                />
                <group name='Torus014' scale={1.602}>
                  <mesh
                    name='Torus014_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus014_0.geometry}
                    material={materials.Root}
                  />
                </group>
              </group>
            </group>
            <group name='Cube007' position={[3.384, 195.027, 10.425]}>
              <mesh
                name='Cube007_0'
                castShadow
                receiveShadow
                geometry={nodes.Cube007_0.geometry}
                // material={materials.material_3}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group name='Torus015'>
                <mesh
                  name='Torus015_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus015_0.geometry}
                  material={materials.Root}
                />
                <group name='Torus016' scale={1.602}>
                  <mesh
                    name='Torus016_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus016_0.geometry}
                    material={materials.Root}
                  />
                </group>
              </group>
            </group>
            <group name='Cube008' position={[-5.611, -152.982, 10.173]}>
              <mesh
                name='Cube008_0'
                castShadow
                receiveShadow
                geometry={nodes.Cube008_0.geometry}
                // material={materials.material_3}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group name='Torus017'>
                <mesh
                  name='Torus017_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus017_0.geometry}
                  material={materials.Root}
                />
                <group name='Torus018' scale={1.602}>
                  <mesh
                    name='Torus018_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus018_0.geometry}
                    material={materials.Root}
                  />
                </group>
              </group>
            </group>
            <group name='Cube009' position={[-6.273, 195.114, 11.325]}>
              <mesh
                name='Cube009_0'
                castShadow
                receiveShadow
                geometry={nodes.Cube009_0.geometry}
                // material={materials.material_3}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group name='Torus019'>
                <mesh
                  name='Torus019_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus019_0.geometry}
                  // material={materials.Root}
                  material={
                    new THREE.MeshStandardMaterial({
                      color: new THREE.Color(0xff4c4c),
                      emissive: new THREE.Color(0xff4c4c),
                      emissiveIntensity: 9,
                      roughness: 0.1,
                      metalness: 0.1,
                      transparent: true,
                      opacity: 0.9,
                      depthWrite: false, //efekat "plutanja"
                    })
                  }
                />
                <group name='Torus020' scale={1.602}>
                  <mesh
                    name='Torus020_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Torus020_0.geometry}
                    material={materials.Root}
                  />
                </group>
              </group>
            </group>
            <group
              name='Circle028'
              position={[-157.941, -157.61, -68.129]}
              rotation={[0, 0, -Math.PI]}
            >
              <mesh
                name='Circle028_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle028_0.geometry}
                // material={materials.material}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group
                name='Circle029'
                position={[0, 0, 45.056]}
                rotation={[0, 0, -Math.PI]}
              >
                <mesh
                  name='Circle029_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle029_0.geometry}
                  material={materials.material}
                />
                <group name='Circle030' position={[-0.738, 0, 8.588]}>
                  <mesh
                    name='Circle030_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle030_0.geometry}
                    material={materials.Root}
                  />
                  <group name='Cube024' position={[-6.407, 4.456, 6.656]}>
                    <mesh
                      name='Cube024_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube024_0.geometry}
                      material={materials.Root}
                    />
                    <group name='Cube025' scale={0}>
                      <mesh
                        name='Cube025_0'
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube025_0.geometry}
                        material={materials["Material.012"]}
                      />
                    </group>
                  </group>
                  <group name='Cube022' position={[-6.407, -4.544, 6.656]}>
                    <mesh
                      name='Cube022_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube022_0.geometry}
                      material={materials.Root}
                    />
                    <group name='Cube023' scale={0}>
                      <mesh
                        name='Cube023_0'
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube023_0.geometry}
                        material={materials["Material.012"]}
                      />
                    </group>
                  </group>
                  <group name='Cube020' position={[-6.407, -4.544, -0.344]}>
                    <mesh
                      name='Cube020_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube020_0.geometry}
                      material={materials.Root}
                    />
                    <group name='Cube021' scale={0}>
                      <mesh
                        name='Cube021_0'
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube021_0.geometry}
                        material={materials["Material.012"]}
                      />
                    </group>
                  </group>
                  <group name='Cube018' position={[-6.407, 4.456, -0.344]}>
                    <mesh
                      name='Cube018_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube018_0.geometry}
                      material={materials.Root}
                    />
                    <group name='Cube019' scale={0}>
                      <mesh
                        name='Cube019_0'
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube019_0.geometry}
                        // material={materials["Material.012"]}
                        material={
                          new THREE.MeshStandardMaterial({
                            color: new THREE.Color(0xff4c4c),
                            emissive: new THREE.Color(0xff4c4c),
                            emissiveIntensity: 9,
                            roughness: 0.1,
                            metalness: 0.1,
                            transparent: true,
                            opacity: 0.9,
                            depthWrite: false, //efekat "plutanja"
                          })
                        }
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group
              name='Circle014'
              position={[-152.087, 145.749, -68.129]}
              rotation={[0, 0, 3.112]}
            >
              <mesh
                name='Circle014_0'
                castShadow
                receiveShadow
                geometry={nodes.Circle014_0.geometry}
                // material={materials.material}
                material={
                  new THREE.MeshStandardMaterial({
                    color: new THREE.Color(0xff4c4c),
                    emissive: new THREE.Color(0xff4c4c),
                    emissiveIntensity: 9,
                    roughness: 0.1,
                    metalness: 0.1,
                    transparent: true,
                    opacity: 0.9,
                    depthWrite: false, //efekat "plutanja"
                  })
                }
              />
              <group
                name='Circle015'
                position={[0, 0, 45.056]}
                rotation={[0, 0, Math.PI]}
              >
                <mesh
                  name='Circle015_0'
                  castShadow
                  receiveShadow
                  geometry={nodes.Circle015_0.geometry}
                  // material={materials.material}
                  material={
                    new THREE.MeshStandardMaterial({
                      color: new THREE.Color(0xff4c4c),
                      emissive: new THREE.Color(0xff4c4c),
                      emissiveIntensity: 9,
                      roughness: 0.1,
                      metalness: 0.1,
                      transparent: true,
                      opacity: 0.9,
                      depthWrite: false, //efekat "plutanja"
                    })
                  }
                />
                <group name='Circle019' position={[-0.738, 0, 8.588]}>
                  <mesh
                    name='Circle019_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle019_0.geometry}
                    material={materials.Root}
                  />
                  <group name='Cube016' position={[-6.407, 4.456, -0.344]}>
                    <mesh
                      name='Cube016_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube016_0.geometry}
                      material={materials.Root}
                    />
                    <group name='Cube017' scale={0}>
                      <mesh
                        name='Cube017_0'
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube017_0.geometry}
                        material={materials["Material.012"]}
                      />
                    </group>
                  </group>
                  <group name='Cube014' position={[-6.407, -4.544, -0.344]}>
                    <mesh
                      name='Cube014_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube014_0.geometry}
                      material={materials.Root}
                    />
                    <group name='Cube015' scale={0}>
                      <mesh
                        name='Cube015_0'
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube015_0.geometry}
                        material={materials["Material.012"]}
                      />
                    </group>
                  </group>
                  <group name='Cube012' position={[-6.407, -4.544, 6.656]}>
                    <mesh
                      name='Cube012_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube012_0.geometry}
                      material={materials.Root}
                    />
                    <group name='Cube013' scale={0}>
                      <mesh
                        name='Cube013_0'
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube013_0.geometry}
                        // material={materials["Material.012"]}
                        material={
                          new THREE.MeshStandardMaterial({
                            color: new THREE.Color(0xff4c4c),
                            emissive: new THREE.Color(0xff4c4c),
                            emissiveIntensity: 9,
                            roughness: 0.1,
                            metalness: 0.1,
                            transparent: true,
                            opacity: 0.9,
                            depthWrite: false, //efekat "plutanja"
                          })
                        }
                      />
                    </group>
                  </group>
                  <group name='Cube010' position={[-6.407, 4.456, 6.656]}>
                    <mesh
                      name='Cube010_0'
                      castShadow
                      receiveShadow
                      geometry={nodes.Cube010_0.geometry}
                      material={materials.Root}
                    />
                    <group name='Cube011' scale={0}>
                      <mesh
                        name='Cube011_0'
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube011_0.geometry}
                        material={materials["Material.012"]}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/aboutModels/space_station.glb");
export default SpaceStation;
