/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gold-star-5296c3fcf6c24e99a07de7cc77cb1209
Title: Gold Star
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const GoldStar = (props) => {
  const { nodes, materials } = useGLTF("/models/space/gold_star.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_Star_0.geometry}
          material={materials.Star}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/space/gold_star.glb");

export default GoldStar;
