/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DeadLink (https://sketchfab.com/hell3879)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smart-littel-robot-dd3ae79fb02944dd94a15826647d014a
Title: Smart Littel Robot
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const LittleRobot = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/proba/little-robot.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      // console.log(actions);
      const action = actions[Object.keys(actions)[0]];
      action.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group
          name='Sketchfab_model'
          rotation={[-Math.PI / 2, 0, 0]}
          scale={168.609}
        >
          <group
            name='3a6b913042bb4c99bfc1a7ed3134eddbfbx'
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name='Object_2'>
              <group name='RootNode'>
                <group name='Object_4'>
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name='Object_6'
                    geometry={nodes.Object_6.geometry}
                    material={materials.Body_lambert}
                    skeleton={nodes.Object_6.skeleton}
                  />
                  <skinnedMesh
                    name='Object_8'
                    geometry={nodes.Object_8.geometry}
                    material={materials.Hand1_lambert}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <skinnedMesh
                    name='Object_10'
                    geometry={nodes.Object_10.geometry}
                    material={materials.Hand_lambert}
                    skeleton={nodes.Object_10.skeleton}
                  />
                  <skinnedMesh
                    name='Object_11'
                    geometry={nodes.Object_11.geometry}
                    material={materials.Legs_lambert}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name='Object_12'
                    geometry={nodes.Object_12.geometry}
                    material={materials.Legs1_lambert}
                    skeleton={nodes.Object_12.skeleton}
                  />
                  <skinnedMesh
                    name='Object_13'
                    geometry={nodes.Object_13.geometry}
                    material={materials.Head_lambert}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <group name='Object_7' />
                  <group name='Object_9' />
                  <group name='Body' />
                  <group name='Hand1' />
                  <group name='Hand' />
                  <group name='Legs' />
                  <group name='Legs1' />
                  <group name='Head' />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/proba/little-robot.glb");

export default LittleRobot;
