/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Berk Gedik (https://sketchfab.com/berkgedik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-turret-animated-d855153c0e844a49b2ccf56c77f178b5
Title: Sci-Fi Turret Animated
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Turret = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/proba/turret.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      // console.log(actions);
      const action = actions[Object.keys(actions)[0]];
      action.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name='c88f7296306d45c7988aad59036bc15dfbx'
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name='Object_2'>
              <group name='RootNode'>
                <group
                  name='Cylinder013'
                  position={[0, 9.798, -107.039]}
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={100}
                >
                  <mesh
                    name='Cylinder013_001_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder013_001_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name='Cylinder016'
                  position={[0, 60.421, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[67.763, 67.763, 17.857]}
                >
                  <mesh
                    name='Cylinder016_001_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder016_001_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name='Cube007'
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name='Cube007_001_0'
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube007_001_0.geometry}
                    material={materials.material}
                  />
                </group>
                <group
                  name='Armature'
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name='Object_11'>
                    <primitive object={nodes._rootJoint} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/proba/turret.glb");

export default Turret;
