/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-robot-sdc-3d127f327a6c4033a32b810b5fb071ed
Title: Animated ROBOT SDC
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const WalkingRobot = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/proba/walking-robot.glb"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      // console.log(actions);
      const action = actions[Object.keys(actions)[0]];
      action.play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group name='Armature_82' rotation={[0, 1.561, 0]}>
                <group name='GLTF_created_0'>
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name='Object_7'
                    geometry={nodes.Object_7.geometry}
                    material={materials.Rubber}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name='Doigts_81' />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/proba/walking-robot.glb");

export default WalkingRobot;
